services:
  - type: worker
    name: spx-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: POLL_MINUTES
        value: "5"
      # - key: PYTHON_VERSION
      #   value: "3.12.7"
